stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "light7787/test-app"
  DOCKER_TAG: "latest"

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main  # or whatever your main branch is called