name: Docker Build and Push

on:
  push:
    branches: [ "main" ]  # Triggers on pushes to main branch
  pull_request:
    branches: [ "main" ]  # Triggers on PRs targeting main

env:
  DOCKER_IMAGE: light7787/test-app # Update this
  DOCKER_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB_USERNAME  # GitHub-hosted runner
    
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to Docker Hub (if pushing to a registry)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

      # 4. Push to Docker Hub (optional)
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE:$DOCKER_TAG